### ISSUE TITLE
The problem of image on the Images

### ISSUE THREAD

**Issue by wbsedu** [minixalpha/minixalpha.github.io#4]
I,m sorry to bother for this problem. 
[my github soure](https://github.com/wbsedu/Ways/blob/gh-pages/_posts/2015-08-26-linux.md)
From the preview, we can see it works normal. 
But in the website [my_personal_blog](http://wbsedu.github.io/Ways/ways/2015/08/26/linux.html)
It cannot show the picture.
I don not know how to correct it.

Thanks

**Comment by minixalpha** [comment]
你看看是不是图片的链接不对 @wbsedu 

你需要注意下面的区别：

https://username.github.io/blogproject/images/foo.png 

https://github.com/username/blogproject/blob/master/images/foo.png

应该写成第一种形式

**Comment by wbsedu** [comment]
谢谢，已经解决了。
